[env]
SURREALDB_SERVER = "localhost"
SURREALDB_PORT = "8000"
SURREALDB_USER = "root"
SURREALDB_PASSWORD = "root"
SURREALDB_NAMESPACE = "SurrealDB"
SURREALDB_DBNAME = "mydatabase"
SURREALDB_TABLENAME = "todos"